version: "3.9"
services:
  play10:
    image: unlimitedrulebook/play10:latest
    container_name: play10
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
    volumes:
      - logs:/logs

volumes:
  logs: